version: '3.9'
services:
    thing1:
        build: ./thing1
        container_name: thing1
        links:
        - thing2:thing1
        ports:
        - 7776:7776
    thing2:
        build: ./thing2
        container_name: thing2
        ports:
        - 7777:7777
    bouncycastle:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'yet_another_leaked_credential'
        ports:
        - 3306:3306
        expose:
        - 3306
        volumes:
        - bouncycastle:/var/lib/mysql
volumes:
    bouncycastle: